### ISSUE TITLE
[Piano] segmentation fault when playing a note

### ISSUE THREAD

**Issue by ycollet** [FigBug/imguru#7]
Sorry to post the bug report here, but the issues are not enabled on your Piano fork.
I built Piano on Fedora 36 and I am not able to use it.
When I play a key on Piano, I've got a segmentation fault:
```
Thread 6 "JUCE ALSA" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff514c640 (LWP 15297)]
ms4 (N=<optimized out>, z=<optimized out>, y=0x5555562a905c, x=<optimized out>) at ../../Source/utils.cpp:100
100             v = simde_mm_sub_ps (simde_mm_shuffle_ps (w, w, SIMDE_MM_SHUFFLE(0, 1, 2, 3)), *x4);
(gdb) where
#0  ms4 (N=<optimized out>, z=<optimized out>, y=0x5555562a905c, x=<optimized out>) at ../../Source/utils.cpp:100
#1  dwgs::tran2long4 (delay=8, this=0x55555629e1e0) at ../../Source/dwgs.cpp:101
#2  dwgs::tran2long4 (delay=8, this=0x55555629e1e0) at ../../Source/dwgs.cpp:32
#3  PianoNote::go4 (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:296
#4  0x00005555557a370d in PianoNote::goDownDelayed (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:148
#5  0x00005555557a42e1 in PianoNote::goDown (this=<optimized out>) at ../../Source/qiano.cpp:138
#6  PianoNote::goUpDelayed (this=this@entry=0x7ffff418e040) at ../../Source/qiano.cpp:113
#7  0x00005555557a46d8 in PianoNote::goUp (this=<optimized out>) at ../../Source/qiano.cpp:99
#8  Piano::process (this=this@entry=0x55555591d720, out=<optimized out>, samples=samples@entry=512) at ../../Source/qiano.cpp:689
#9  0x00005555557a81d2 in Piano::process (offset=<optimized out>, samples=<optimized out>, out=0x7ffff514b980, this=0x55555591d720) at ../../Source/qiano.cpp:708
#10 Piano::process (this=<optimized out>, outS=<optimized out>, sampleFrames=<optimized out>, midi=...) at ../../Source/qiano.cpp:765
#11 0x00005555555d16e1 in PianoAudioProcessor::processBlock (this=0x55555591d3c0, buffer=..., midi=...)
    at ../../../modules/juce/modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.h:242
#12 0x00005555556467c5 in juce::AudioProcessorPlayer::audioDeviceIOCallbackWithContext (this=<optimized out>, inputChannelData=<optimized out>, 
    numInputChannels=<optimized out>, outputChannelData=<optimized out>, numOutputChannels=<optimized out>, numSamples=<optimized out>, context=...)
    at ../../../modules/juce/modules/juce_audio_utils/players/juce_AudioProcessorPlayer.cpp:328
#13 0x00005555555c1c15 in juce::StandalonePluginHolder::CallbackMaxSizeEnforcer::audioDeviceIOCallbackWithContext (this=0x55555591d370, inputChannelData=0x0, 
    numInputChannels=<optimized out>, outputChannelData=0x5555559f8f70, numOutputChannels=<optimized out>, numSamples=512, context=...)
    at ../../../modules/juce/modules/juce_audio_plugin_client/Standalone/juce_StandaloneFilterWindow.h:469
#14 0x0000555555624d5c in juce::AudioDeviceManager::audioDeviceIOCallbackInt (context=..., numSamples=512, numOutputChannels=2, outputChannelData=0x5555559f8f70, 
    numInputChannels=0, inputChannelData=0x0, this=0x55555591cb70) at ../../../modules/juce/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:1002
#15 juce::AudioDeviceManager::CallbackHandler::audioDeviceIOCallbackWithContext (this=<optimized out>, ins=0x0, numIns=0, outs=0x5555559f8f70, numOuts=2, 
    numSamples=512, context=...) at ../../../modules/juce/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:79
#16 0x000055555561f705 in juce::(anonymous namespace)::ALSAThread::run (this=0x555555a02560) at ../../../modules/juce/modules/juce_core/memory/juce_HeapBlock.h:182
#17 0x000055555566eb5c in juce::Thread::createNativeThread(juce::Thread::Priority)::{lambda(void*)#1}::_FUN(void*) [clone .lto_priv.0] ()
    at ../../../modules/juce/modules/juce_core/threads/juce_Thread.cpp:98
#18 0x00007ffff768cdcd in start_thread (arg=<optimized out>) at pthread_create.c:442
#19 0x00007ffff7712630 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by FigBug** [comment]
I've enabled issues, please repost in correct repo.

**Comment by ycollet** [comment]
OK
